[package]
name = "aoc_2022"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "aoc_2022"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.4", features = ["derive"] }
